### ISSUE TITLE
2019/10/12|Set up grade model

### ISSUE THREAD

**Issue by umepon0626** [miraiproject/GouniteQuest#1]
#### 必ずすべての箇所を記入してください！じゃないと困ります！

    - **Please explain the problem to solve with screenshots (どんな問題があるか,スクショもつけてください):**
grade modelを作ってもらう

    - **Where does the problem exist ? (その問題はどこで発生していますか？):**
quest/models.py
    **Solution (解決策):**
[このドキュメント](https://docs.google.com/document/d/1mJmM7m1zaQw4YNfdA-1oHRURXu6tnABY2a7m125IhmI/edit)

    **Time estimated to complete (完了推定時間):**
2h

## Task checklist (タスクチェックリスト)

    - [ ] Investigate flows
    - [ ] investigate user model
    - [ ] set up grade model

## Checklist to complete before closing the issue (イシューを閉じる前のチェックリスト)

- [x] Please check the status of our App in your local environment. Does your solution work properly? (ローカル環境でアプリの状態を確認してください。あなたの解決策は正しく機能していますか？)
- [x] Label `WIP` has been unset (`WIP`ラベルが設定されていないか)
- [ ] Notify coworkers if they need to take specific actions following your
  merge in master
- [ ] Overview written (Overviewを記入する)
- [ ] [Evaluation form](https://goo.gl/forms/J3Dc4pMKPefURskw1) with
  CTO evaluation scores.

## Overview

**Investigation time (調査時間）：1h**
**Implementation time (実装時間）：1h**

**Comment by umepon0626** [comment]
LGTM
