### ISSUE TITLE
2019/10/13|Set up views.py

### ISSUE THREAD

**Issue by umepon0626** [miraiproject/GouniteQuest#2]
## Task Description (タスク詳細)
以下の要件を満たすviewを書いてください。
- 各科目の点数を受け取り、保存する。
- 各科目の点数の一覧と名前を返す。

#### 必ずすべての箇所を記入してください！じゃないと困ります！

    - **Please explain the problem to solve with screenshots (どんな問題があるか,スクショもつけてください):**

    - **Where does the problem exist ? (その問題はどこで発生していますか？):**

http://reachat.local:8000/path/to/page

    **Solution (解決策):**

    **Time estimated to complete (完了推定時間):**

## Task checklist (タスクチェックリスト)

    ##For example
    ##Each description
    - [ ] Investigate flows
    - [ ] Fix wagtail_hooks.py
    - [ ] …

## Checklist to complete before closing the issue (イシューを閉じる前のチェックリスト)

- [ ] Please check the status of our App in your local environment. Does your solution work properly? (ローカル環境でアプリの状態を確認してください。あなたの解決策は正しく機能していますか？)
- [ ] Label `WIP` has been unset (`WIP`ラベルが設定されていないか)
- [ ] Notify coworkers if they need to take specific actions following your
  merge in master
- [ ] Overview written (Overviewを記入する)
- [ ] [Evaluation form](https://goo.gl/forms/J3Dc4pMKPefURskw1) with
  CTO evaluation scores.

## Overview

**Investigation time (調査時間）：**
**Implementation time (実装時間）：**
